[versions]
appcompatVersion = "1.7.1"
ccp = "2.7.3"
composeBom = "2025.11.01"
core = "4.6.2"
desugar_jdk_libs = "2.1.5"
editorBom = "0.23.7"
firebaseBom = "34.6.0"
glide = "4.12.0"
gson = "2.13.1"
guava = "32.1.3-android"
image = "4.6.2"
jsoup = "1.17.2"
junit = "4.13.2"
junitVersion = "1.3.0"
espressoCore = "3.7.0"
appcompat = "1.7.1"
libphonenumber = "8.13.38"
lifecycleViewmodelKtx = "2.10.0"
material = "1.13.0"
activity = "1.12.0"
constraintlayout = "2.2.1"
foundation = "1.9.5"
foundationLayout = "1.9.5"
materialIconsExtended = "1.7.8"
materialVersion = "1.13.0"
okhttp = "4.12.0"
playServicesAuth = "21.4.0"
recyclerview = "1.4.0"

[libraries]
androidx-compose-bom = { module = "androidx.compose:compose-bom", version.ref = "composeBom" }
androidx-foundation = { module = "androidx.compose.foundation:foundation" }
androidx-lifecycle-viewmodel-ktx = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "lifecycleViewmodelKtx" }
androidx-material-icons-extended = { module = "androidx.compose.material:material-icons-extended", version.ref = "materialIconsExtended" }
androidx-recyclerview = { module = "androidx.recyclerview:recyclerview", version.ref = "recyclerview" }
androidx-runtime-livedata = { module = "androidx.compose.runtime:runtime-livedata" }
androidx-ui-test-junit4 = { module = "androidx.compose.ui:ui-test-junit4" }
androidx-ui-test-manifest = { module = "androidx.compose.ui:ui-test-manifest" }
androidx-ui-tooling = { module = "androidx.compose.ui:ui-tooling" }
androidx-ui-tooling-preview = { module = "androidx.compose.ui:ui-tooling-preview" }
appcompat-v171 = { module = "androidx.appcompat:appcompat", version.ref = "appcompatVersion" }
ccp = { module = "com.hbb20:ccp", version.ref = "ccp" }
core = { module = "io.noties.markwon:core", version.ref = "core" }
desugar_jdk_libs = { module = "com.android.tools:desugar_jdk_libs", version.ref = "desugar_jdk_libs" }
editor = { module = "io.github.rosemoe:editor" }
editor-bom = { module = "io.github.rosemoe:editor-bom", version.ref = "editorBom" }
firebase-auth = { module = "com.google.firebase:firebase-auth" }
firebase-bom = { module = "com.google.firebase:firebase-bom", version.ref = "firebaseBom" }
firebase-firestore = { module = "com.google.firebase:firebase-firestore" }
glide = { module = "com.github.bumptech.glide:glide", version.ref = "glide" }
gson = { module = "com.google.code.gson:gson", version.ref = "gson" }
guava = { module = "com.google.guava:guava", version.ref = "guava" }
image = { module = "io.noties.markwon:image", version.ref = "image" }
jsoup = { module = "org.jsoup:jsoup", version.ref = "jsoup" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
ext-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
language-textmate = { module = "io.github.rosemoe:language-textmate" }
libphonenumber = { module = "com.googlecode.libphonenumber:libphonenumber", version.ref = "libphonenumber" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
activity = { group = "androidx.activity", name = "activity", version.ref = "activity" }
constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }
foundation = { group = "androidx.compose.foundation", name = "foundation", version.ref = "foundation" }
foundation-layout = { group = "androidx.compose.foundation", name = "foundation-layout", version.ref = "foundationLayout" }
material-v1130 = { module = "com.google.android.material:material", version.ref = "materialVersion" }
material3 = { module = "androidx.compose.material3:material3", version = "1.4.0" }
okhttp = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp" }
play-services-auth = { module = "com.google.android.gms:play-services-auth", version.ref = "playServicesAuth" }
ui = { module = "androidx.compose.ui:ui" }

[plugins]

